spring:
#docker run --name postgreebanco -e POSTGRES_PASSWORD=123456 -d -p 5423:5432 postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/eateasy
    username: dev
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    database: postgresql
    database-plataform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
